<?php
namespace CheckList\Controller;

use Zend\Mvc\Controller\AbstractActionController;

class TaskController extends AbstractActionController{
    public function indexAction(){
        $coder = "<p>author: Anh Le Hoang</p>";
        $coder .= "<br><code>^^</code>";
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
    public function addAction(){
        return parent::indexAction();
    }
    public function editAction(){
        return parent::indexAction();
    }
    public function deleteAction(){
        return parent::indexAction();
    }

}